### ISSUE TITLE
Generate HTML output

### ISSUE THREAD

**Issue by jubalh** [jubalh/contriblister#2]
Generate HTML output so one can include this in a static blog (jekyll/hugo) and have a nice overview over ones open source contributions.

Maybe use [jinja](http://jinja.pocoo.org/) to templating.

**Comment by ghost** [comment]
Since b0620451571550598ad9d5531c19af8b2058be9b the script does output the contributions as HTML-table.

TODO:
- IDs/Classes to affort the usage of custom CSS/JavaScript
- Sorting (do we really want this? see point above)

**Comment by jubalh** [comment]
Nice work!
I think we should start using jinja. It would be nice to have a general template. But we want the user give the ability to tweak this without having to dig into the python code just by customizing the jinja template to his needs.

**Comment by jubalh** [comment]
Closed by fa293375db5a609f9f5fa71a777b756aa810ee6c
